import type { Metadata } from "next";
import Link from "next/link";
import { tools } from "@/lib/data";

export const metadata: Metadata = {
    title: "Free AI Caption Generator — Instagram & Social Media | Zehbee",
    description: "Generate smart, engaging AI captions for your images instantly. Free, no signup required. Perfect for Instagram, Twitter, and social media.",
    alternates: { canonical: "https://zehbee.com/ai-caption" },
    openGraph: {
        title: "Free AI Caption Generator — Zehbee",
        description: "Generate smart AI captions for your images — free, no signup.",
        url: "https://zehbee.com/ai-caption",
        siteName: "Zehbee",
        type: "website",
    },
};

const faqs = [
    {
        q: "How does the AI Caption Generator work?",
        a: "Upload your image and our AI analyzes the content, context, and mood to generate relevant, engaging captions tailored for social media.",
    },
    {
        q: "Can I use the captions for Instagram?",
        a: "Yes. The captions are optimized for social media platforms including Instagram, Twitter, LinkedIn, and Facebook.",
    },
    {
        q: "How many captions does it generate?",
        a: "The tool generates multiple caption options so you can pick the one that best fits your post's tone — casual, professional, or creative.",
    },
    {
        q: "Is my image stored or used for training?",
        a: "No. Your images are processed temporarily in your session and are never stored or used for AI training.",
    },
];

const howToSteps = [
    {
        title: "Upload your image",
        desc: "Click to upload or drag and drop the image you want a caption for. Works with JPG, PNG, and WEBP.",
    },
    {
        title: "Choose your tone",
        desc: "Select a tone — casual, professional, humorous, or inspirational — to guide the AI's output.",
    },
    {
        title: "Generate & copy",
        desc: "Click Generate and get multiple caption options instantly. Copy your favorite with one click.",
    },
];

const relatedTools = tools.filter((t) => t.href !== "/ai-caption").slice(0, 4);

export default function AiCaptionPage() {
    return (
        <>


            <header className="tool-page-hero">
                <div className="container">
                    <Link href="/" className="tool-page-badge">
                        <svg width="12" height="12" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
                        </svg>
                        Back to all tools
                    </Link>
                    <h1 className="tool-page-title">AI Caption Generator</h1>
                    <p className="tool-page-desc">
                        Upload any image and get smart, engaging captions generated by AI — perfect
                        for Instagram, Twitter, and all social media platforms.
                    </p>
                    <div className="tool-page-trust">
                        {["Free forever", "No signup needed", "Multiple tones", "Instant results"].map((t) => (
                            <div className="tool-trust-item" key={t}>
                                <svg width="13" height="13" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                                </svg>
                                {t}
                            </div>
                        ))}
                    </div>
                </div>
            </header>

            <div className="container" style={{ paddingTop: "1.5rem" }}>
                <div className="ad-slot">Advertisement</div>
            </div>

            <div className="tool-ui-section">
                <div className="container">
                    <div className="tool-ui-box">
                        <div className="tool-ui-placeholder">
                            <svg width="48" height="48" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" d="M7.5 8.25h9m-9 3H12m-9.75 1.51c0 1.6 1.123 2.994 2.707 3.227 1.129.166 2.27.293 3.423.379.35.026.67.21.865.501L12 21l2.755-4.133a1.14 1.14 0 01.865-.501 48.172 48.172 0 003.423-.379c1.584-.233 2.707-1.626 2.707-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
                            </svg>
                            <p>Upload an image to generate AI-powered captions</p>
                        </div>
                    </div>
                </div>
            </div>

            <section>
                <div className="container">
                    <div className="section">
                        <div className="section-header">
                            <span className="section-label">About This Tool</span>
                            <h2 className="section-title">What is an AI Caption Generator?</h2>
                        </div>
                        <div className="seo-body" style={{ maxWidth: 720 }}>
                            <p>
                                An AI Caption Generator uses machine learning to analyze your image and
                                produce relevant, creative captions suited for social media. Instead of
                                spending time writing captions, you get multiple high-quality options in seconds.
                            </p>
                            <p>
                                Zehbee&apos;s Caption Generator understands context, objects, emotions, and settings
                                in your photo — then produces captions that match the mood and platform you&apos;re
                                posting to. Great for content creators, brands, and social media managers.
                            </p>
                            <p>
                                You can choose the tone — from casual and fun to professional and inspiring —
                                and get a selection of captions to choose from. Copy with one click and you&apos;re done.
                            </p>
                        </div>
                    </div>
                </div>
            </section>

            <div style={{ background: "var(--surface)", borderTop: "1px solid var(--border)", borderBottom: "1px solid var(--border)" }}>
                <div className="container">
                    <div className="section">
                        <div className="section-header">
                            <span className="section-label">Guide</span>
                            <h2 className="section-title">How to generate AI captions</h2>
                        </div>
                        <ol className="how-steps">
                            {howToSteps.map((step, i) => (
                                <li key={step.title} className="how-step">
                                    <span className="how-step-num">{i + 1}</span>
                                    <div className="how-step-content">
                                        <h3>{step.title}</h3>
                                        <p>{step.desc}</p>
                                    </div>
                                </li>
                            ))}
                        </ol>
                    </div>
                </div>
            </div>

            <div className="container" style={{ paddingTop: "3rem" }}>
                <div className="ad-slot">Advertisement</div>
            </div>

            <section aria-labelledby="faq-heading">
                <div className="container">
                    <div className="section">
                        <div className="section-header">
                            <span className="section-label">FAQ</span>
                            <h2 id="faq-heading" className="section-title">Frequently asked questions</h2>
                        </div>
                        <dl className="faq-list">
                            {faqs.map((faq) => (
                                <div key={faq.q} className="faq-item">
                                    <dt className="faq-q">{faq.q}</dt>
                                    <dd className="faq-a">{faq.a}</dd>
                                </div>
                            ))}
                        </dl>
                    </div>
                </div>
            </section>

            <section style={{ paddingTop: 0 }}>
                <div className="container">
                    <div className="section" style={{ paddingTop: 0 }}>
                        <div className="section-header">
                            <span className="section-label">More Tools</span>
                            <h2 className="section-title">You might also like</h2>
                        </div>
                        <ul className="related-grid">
                            {relatedTools.map((tool) => (
                                <li key={tool.href}>
                                    <Link href={tool.href} className="related-card">
                                        <div className="related-icon" style={{ color: tool.accent }}>{tool.icon}</div>
                                        <div>
                                            <p className="related-name">{tool.title}</p>
                                            <p className="related-desc">{tool.description}</p>
                                        </div>
                                    </Link>
                                </li>
                            ))}
                        </ul>
                    </div>
                </div>
            </section>

            <div className="container" style={{ paddingBottom: "3rem" }}>
                <div className="ad-slot">Advertisement</div>
            </div>


        </>
    );
}