import type { Metadata } from "next";
import Link from "next/link";
import { tools } from "@/lib/data";

export const metadata: Metadata = {
    title: "Free QR Code Generator — URLs, Text & Contact Info | Zehbee",
    description: "Generate QR codes for URLs, text, email, phone numbers, and contact cards. Free, instant download, no signup required.",
    alternates: { canonical: "https://zehbee.com/qr-generator" },
    openGraph: {
        title: "Free QR Code Generator — Zehbee",
        description: "Generate QR codes for any URL, text, or contact info — free, instant download.",
        url: "https://zehbee.com/qr-generator",
        siteName: "Zehbee",
        type: "website",
    },
};

const faqs = [
    {
        q: "What can I create a QR code for?",
        a: "You can generate QR codes for URLs, plain text, email addresses, phone numbers, Wi-Fi credentials, and contact cards (vCard).",
    },
    {
        q: "Can I customize the QR code design?",
        a: "Yes — you can change the color, size, and add a logo or icon in the center of your QR code.",
    },
    {
        q: "What format can I download the QR code in?",
        a: "You can download your QR code as PNG or SVG. SVG is recommended for print as it scales without any quality loss.",
    },
    {
        q: "Do the QR codes expire?",
        a: "No. The QR codes generated by Zehbee are static and never expire. They will work forever as long as the destination URL is live.",
    },
];

const howToSteps = [
    {
        title: "Choose your content type",
        desc: "Select what your QR code should link to — a URL, text, email, phone number, or contact card.",
    },
    {
        title: "Enter your content",
        desc: "Type or paste the URL, text, or contact details you want encoded in the QR code.",
    },
    {
        title: "Download your QR code",
        desc: "Click Generate and download your QR code as PNG or SVG. Ready to use instantly.",
    },
];

const relatedTools = tools.filter((t) => t.href !== "/qr-generator").slice(0, 4);

export default function QrGeneratorPage() {
    return (
        <>


            <header className="tool-page-hero">
                <div className="container">
                    <Link href="/" className="tool-page-badge">
                        <svg width="12" height="12" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
                        </svg>
                        Back to all tools
                    </Link>
                    <h1 className="tool-page-title">QR Code Generator</h1>
                    <p className="tool-page-desc">
                        Generate QR codes for any URL, text, or contact info — download instantly
                        as PNG or SVG, completely free with no account required.
                    </p>
                    <div className="tool-page-trust">
                        {["Free forever", "No signup needed", "PNG & SVG export", "Never expires"].map((t) => (
                            <div className="tool-trust-item" key={t}>
                                <svg width="13" height="13" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                                </svg>
                                {t}
                            </div>
                        ))}
                    </div>
                </div>
            </header>

            <div className="container" style={{ paddingTop: "1.5rem" }}>
                <div className="ad-slot">Advertisement</div>
            </div>

            <div className="tool-ui-section">
                <div className="container">
                    <div className="tool-ui-box">
                        <div className="tool-ui-placeholder">
                            <svg width="48" height="48" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 4.875c0-.621.504-1.125 1.125-1.125h4.5c.621 0 1.125.504 1.125 1.125v4.5c0 .621-.504 1.125-1.125 1.125h-4.5A1.125 1.125 0 013.75 9.375v-4.5zM3.75 14.625c0-.621.504-1.125 1.125-1.125h4.5c.621 0 1.125.504 1.125 1.125v4.5c0 .621-.504 1.125-1.125 1.125h-4.5a1.125 1.125 0 01-1.125-1.125v-4.5zM13.5 4.875c0-.621.504-1.125 1.125-1.125h4.5c.621 0 1.125.504 1.125 1.125v4.5c0 .621-.504 1.125-1.125 1.125h-4.5A1.125 1.125 0 0113.5 9.375v-4.5z" />
                            </svg>
                            <p>Enter a URL or text to generate your QR code</p>
                        </div>
                    </div>
                </div>
            </div>

            <section>
                <div className="container">
                    <div className="section">
                        <div className="section-header">
                            <span className="section-label">About This Tool</span>
                            <h2 className="section-title">What is a QR Code Generator?</h2>
                        </div>
                        <div className="seo-body" style={{ maxWidth: 720 }}>
                            <p>
                                A QR code (Quick Response code) is a type of 2D barcode that can be scanned
                                by any smartphone camera to instantly open a URL, display text, save a contact,
                                or connect to Wi-Fi — without any typing.
                            </p>
                            <p>
                                Zehbee&apos;s QR Code Generator creates high-quality, scannable QR codes in seconds.
                                You can customize the color and size, and download as PNG for digital use or SVG
                                for print-quality output that scales to any size.
                            </p>
                            <p>
                                QR codes are perfect for business cards, restaurant menus, product packaging,
                                event flyers, presentations, and anywhere you want to bridge physical and digital.
                            </p>
                        </div>
                    </div>
                </div>
            </section>

            <div style={{ background: "var(--surface)", borderTop: "1px solid var(--border)", borderBottom: "1px solid var(--border)" }}>
                <div className="container">
                    <div className="section">
                        <div className="section-header">
                            <span className="section-label">Guide</span>
                            <h2 className="section-title">How to create a QR code</h2>
                        </div>
                        <ol className="how-steps">
                            {howToSteps.map((step, i) => (
                                <li key={step.title} className="how-step">
                                    <span className="how-step-num">{i + 1}</span>
                                    <div className="how-step-content">
                                        <h3>{step.title}</h3>
                                        <p>{step.desc}</p>
                                    </div>
                                </li>
                            ))}
                        </ol>
                    </div>
                </div>
            </div>

            <div className="container" style={{ paddingTop: "3rem" }}>
                <div className="ad-slot">Advertisement</div>
            </div>

            <section aria-labelledby="faq-heading">
                <div className="container">
                    <div className="section">
                        <div className="section-header">
                            <span className="section-label">FAQ</span>
                            <h2 id="faq-heading" className="section-title">Frequently asked questions</h2>
                        </div>
                        <dl className="faq-list">
                            {faqs.map((faq) => (
                                <div key={faq.q} className="faq-item">
                                    <dt className="faq-q">{faq.q}</dt>
                                    <dd className="faq-a">{faq.a}</dd>
                                </div>
                            ))}
                        </dl>
                    </div>
                </div>
            </section>

            <section style={{ paddingTop: 0 }}>
                <div className="container">
                    <div className="section" style={{ paddingTop: 0 }}>
                        <div className="section-header">
                            <span className="section-label">More Tools</span>
                            <h2 className="section-title">You might also like</h2>
                        </div>
                        <ul className="related-grid">
                            {relatedTools.map((tool) => (
                                <li key={tool.href}>
                                    <Link href={tool.href} className="related-card">
                                        <div className="related-icon" style={{ color: tool.accent }}>{tool.icon}</div>
                                        <div>
                                            <p className="related-name">{tool.title}</p>
                                            <p className="related-desc">{tool.description}</p>
                                        </div>
                                    </Link>
                                </li>
                            ))}
                        </ul>
                    </div>
                </div>
            </section>

            <div className="container" style={{ paddingBottom: "3rem" }}>
                <div className="ad-slot">Advertisement</div>
            </div>


        </>
    );
}