import type { Metadata } from "next";
import Link from "next/link";
import { tools } from "@/lib/data";

export const metadata: Metadata = {
    title: "Free Text to Speech Online — Natural Voices | Zehbee",
    description: "Convert any text to natural sounding audio instantly. Free text to speech tool with multiple voices and languages. No signup required.",
    alternates: { canonical: "https://zehbee.com/text-to-speech" },
    openGraph: {
        title: "Free Text to Speech — Zehbee",
        description: "Convert text to natural audio instantly — free, multiple voices, no signup.",
        url: "https://zehbee.com/text-to-speech",
        siteName: "Zehbee",
        type: "website",
    },
};

const faqs = [
    {
        q: "How many characters can I convert at once?",
        a: "You can convert up to 5,000 characters per conversion for free. For longer texts, simply split them into sections.",
    },
    {
        q: "What voices and languages are available?",
        a: "Multiple natural-sounding voices are available in English and other major languages. You can preview each voice before generating.",
    },
    {
        q: "What format is the audio downloaded in?",
        a: "Audio is downloaded as an MP3 file, which is compatible with all devices and media players.",
    },
    {
        q: "Can I use the audio for commercial projects?",
        a: "Yes. Audio generated by Zehbee&apos;s Text to Speech tool is free to use for personal and commercial projects.",
    },
];

const howToSteps = [
    {
        title: "Type or paste your text",
        desc: "Enter the text you want to convert to speech in the input box. You can type directly or paste from anywhere.",
    },
    {
        title: "Choose a voice",
        desc: "Select a voice and language from the available options. Click preview to hear a sample before generating.",
    },
    {
        title: "Generate & download",
        desc: "Click Convert to Speech and download your MP3 audio file instantly. No waiting, no account needed.",
    },
];

const relatedTools = tools.filter((t) => t.href !== "/text-to-speech");

export default function TextToSpeechPage() {
    return (
        <>


            <header className="tool-page-hero">
                <div className="container">
                    <Link href="/" className="tool-page-badge">
                        <svg width="12" height="12" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
                        </svg>
                        Back to all tools
                    </Link>
                    <h1 className="tool-page-title">Text to Speech</h1>
                    <p className="tool-page-desc">
                        Convert any text into natural sounding audio instantly — multiple voices,
                        multiple languages, free to use with no account required.
                    </p>
                    <div className="tool-page-trust">
                        {["Free forever", "No signup needed", "Natural voices", "MP3 download"].map((t) => (
                            <div className="tool-trust-item" key={t}>
                                <svg width="13" height="13" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                                </svg>
                                {t}
                            </div>
                        ))}
                    </div>
                </div>
            </header>

            <div className="container" style={{ paddingTop: "1.5rem" }}>
                <div className="ad-slot">Advertisement</div>
            </div>

            <div className="tool-ui-section">
                <div className="container">
                    <div className="tool-ui-box">
                        <div className="tool-ui-placeholder">
                            <svg width="48" height="48" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" d="M19.114 5.636a9 9 0 010 12.728M16.463 8.288a5.25 5.25 0 010 7.424M6.75 8.25l4.72-4.72a.75.75 0 011.28.53v15.88a.75.75 0 01-1.28.53l-4.72-4.72H4.51c-.88 0-1.704-.507-1.938-1.354A9.01 9.01 0 012.25 12c0-.83.112-1.633.322-2.396C2.806 8.756 3.63 8.25 4.51 8.25H6.75z" />
                            </svg>
                            <p>Type or paste your text to convert it to speech</p>
                        </div>
                    </div>
                </div>
            </div>

            <section>
                <div className="container">
                    <div className="section">
                        <div className="section-header">
                            <span className="section-label">About This Tool</span>
                            <h2 className="section-title">What is Text to Speech?</h2>
                        </div>
                        <div className="seo-body" style={{ maxWidth: 720 }}>
                            <p>
                                Text to Speech (TTS) is technology that converts written text into spoken audio.
                                It&apos;s used for creating voiceovers, accessibility tools, audiobooks, podcast intros,
                                e-learning content, and much more — all without needing a microphone or recording setup.
                            </p>
                            <p>
                                Zehbee&apos;s Text to Speech tool uses natural-sounding AI voices that don&apos;t sound robotic.
                                You get clear, expressive audio that&apos;s suitable for professional use — video narrations,
                                explainer content, social media reels, and more.
                            </p>
                            <p>
                                Simply type or paste your text, pick a voice, and download your MP3. No account,
                                no subscriptions, no limits on how often you use it.
                            </p>
                        </div>
                    </div>
                </div>
            </section>

            <div style={{ background: "var(--surface)", borderTop: "1px solid var(--border)", borderBottom: "1px solid var(--border)" }}>
                <div className="container">
                    <div className="section">
                        <div className="section-header">
                            <span className="section-label">Guide</span>
                            <h2 className="section-title">How to convert text to speech</h2>
                        </div>
                        <ol className="how-steps">
                            {howToSteps.map((step, i) => (
                                <li key={step.title} className="how-step">
                                    <span className="how-step-num">{i + 1}</span>
                                    <div className="how-step-content">
                                        <h3>{step.title}</h3>
                                        <p>{step.desc}</p>
                                    </div>
                                </li>
                            ))}
                        </ol>
                    </div>
                </div>
            </div>

            <div className="container" style={{ paddingTop: "3rem" }}>
                <div className="ad-slot">Advertisement</div>
            </div>

            <section aria-labelledby="faq-heading">
                <div className="container">
                    <div className="section">
                        <div className="section-header">
                            <span className="section-label">FAQ</span>
                            <h2 id="faq-heading" className="section-title">Frequently asked questions</h2>
                        </div>
                        <dl className="faq-list">
                            {faqs.map((faq) => (
                                <div key={faq.q} className="faq-item">
                                    <dt className="faq-q">{faq.q}</dt>
                                    <dd className="faq-a">{faq.a}</dd>
                                </div>
                            ))}
                        </dl>
                    </div>
                </div>
            </section>

            <section style={{ paddingTop: 0 }}>
                <div className="container">
                    <div className="section" style={{ paddingTop: 0 }}>
                        <div className="section-header">
                            <span className="section-label">More Tools</span>
                            <h2 className="section-title">You might also like</h2>
                        </div>
                        <ul className="related-grid">
                            {relatedTools.map((tool) => (
                                <li key={tool.href}>
                                    <Link href={tool.href} className="related-card">
                                        <div className="related-icon" style={{ color: tool.accent }}>{tool.icon}</div>
                                        <div>
                                            <p className="related-name">{tool.title}</p>
                                            <p className="related-desc">{tool.description}</p>
                                        </div>
                                    </Link>
                                </li>
                            ))}
                        </ul>
                    </div>
                </div>
            </section>

            <div className="container" style={{ paddingBottom: "3rem" }}>
                <div className="ad-slot">Advertisement</div>
            </div>


        </>
    );
}